# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Matrix_Mult <- function(A, B, n_cores = 4L) {
    .Call(`_ECSLRx_Matrix_Mult`, A, B, n_cores)
}

Matrix_crossprod <- function(A, B, n_cores = 4L) {
    .Call(`_ECSLRx_Matrix_crossprod`, A, B, n_cores)
}

Soft <- function(z, gamma) {
    .Call(`_ECSLRx_Soft`, z, gamma)
}

group_norm <- function(s, Group_Matrix) {
    .Call(`_ECSLRx_group_norm`, s, Group_Matrix)
}

group_soft_thresh <- function(vv, ue, Group_Matrix) {
    .Call(`_ECSLRx_group_soft_thresh`, vv, ue, Group_Matrix)
}

sigmoid <- function(z) {
    .Call(`_ECSLRx_sigmoid`, z)
}

Compute_penalty_sparsity_Lasso <- function(m, betas, w_lasso, lambda_lasso) {
    .Call(`_ECSLRx_Compute_penalty_sparsity_Lasso`, m, betas, w_lasso, lambda_lasso)
}

Compute_penalty_sparsity_groupLasso <- function(m, betas, Group_Matrix, w_group, lambda_group) {
    .Call(`_ECSLRx_Compute_penalty_sparsity_groupLasso`, m, betas, Group_Matrix, w_group, lambda_group)
}

Compute_penalty_fused <- function(m, betas, fused_penmat, lambda_fused) {
    .Call(`_ECSLRx_Compute_penalty_fused`, m, betas, fused_penmat, lambda_fused)
}

Compute_penalty_diversity_group <- function(m, betas, Group_Matrix, w_group, lambda_diversity) {
    .Call(`_ECSLRx_Compute_penalty_diversity_group`, m, betas, Group_Matrix, w_group, lambda_diversity)
}

Compute_AEC <- function(scores, y, cost_matrix) {
    .Call(`_ECSLRx_Compute_AEC`, scores, y, cost_matrix)
}

Compute_objective_multi <- function(m, x_std, y, cost_matrix, lambda_lasso, lambda_group, lambda_fused, lambda_diversity, w_lasso, w_group, Group_Matrix, fused_penmat, betas, intercept) {
    .Call(`_ECSLRx_Compute_objective_multi`, m, x_std, y, cost_matrix, lambda_lasso, lambda_group, lambda_fused, lambda_diversity, w_lasso, w_group, Group_Matrix, fused_penmat, betas, intercept)
}

Compute_objective_ensemble_multi <- function(M, x_std, y, cost_matrix, lambda_lasso, lambda_group, lambda_fused, lambda_diversity, w_lasso, w_group, Group_Matrix, fused_penmat, betas, intercept) {
    .Call(`_ECSLRx_Compute_objective_ensemble_multi`, M, x_std, y, cost_matrix, lambda_lasso, lambda_group, lambda_fused, lambda_diversity, w_lasso, w_group, Group_Matrix, fused_penmat, betas, intercept)
}

admm_flasso <- function(vv, Group_Matrix, Adjust_Matrix_Fused, lambda_3, fused_penmat, Q, eigval, max_iter_admm, betas_old, numfused, df, iter_count) {
    .Call(`_ECSLRx_admm_flasso`, vv, Group_Matrix, Adjust_Matrix_Fused, lambda_3, fused_penmat, Q, eigval, max_iter_admm, betas_old, numfused, df, iter_count)
}

compute_block_eigen <- function(Group_Matrix, Adjust_Matrix_Fused, fused_penmat) {
    .Call(`_ECSLRx_compute_block_eigen`, Group_Matrix, Adjust_Matrix_Fused, fused_penmat)
}

update_betas <- function(vv, betas_old, Group_Matrix, Adjust_Matrix_Fused, fused_penmat, Q, eigval, numfused, df, max_iter_admm, lambda_lasso, w_lasso, lambda_fused, group_soft_penalty, eta_m, exist_grouplasso, lambda_1w, lambda_2, lambda_3) {
    .Call(`_ECSLRx_update_betas`, vv, betas_old, Group_Matrix, Adjust_Matrix_Fused, fused_penmat, Q, eigval, numfused, df, max_iter_admm, lambda_lasso, w_lasso, lambda_fused, group_soft_penalty, eta_m, exist_grouplasso, lambda_1w, lambda_2, lambda_3)
}

update_betas_with_iter <- function(vv, betas_old, Group_Matrix, Adjust_Matrix_Fused, fused_penmat, Q, eigval, numfused, df, max_iter_admm, lambda_lasso, w_lasso, lambda_fused, group_soft_penalty, eta_m, exist_grouplasso) {
    .Call(`_ECSLRx_update_betas_with_iter`, vv, betas_old, Group_Matrix, Adjust_Matrix_Fused, fused_penmat, Q, eigval, numfused, df, max_iter_admm, lambda_lasso, w_lasso, lambda_fused, group_soft_penalty, eta_m, exist_grouplasso)
}

ECSLR_Compute_Coef_combine <- function(x, y, cost_matrix, M, include_intercept, w_lasso, Group_Matrix, w_group, Adjust_Matrix_Fused, fused_penmat, alpha, gamma, lambda_sparsity, lambda_diversity, tolerance, obj_tol_rel, max_iter, max_iter_admm, model, x0_ = NULL, eigen_cache_ = NULL) {
    .Call(`_ECSLRx_ECSLR_Compute_Coef_combine`, x, y, cost_matrix, M, include_intercept, w_lasso, Group_Matrix, w_group, Adjust_Matrix_Fused, fused_penmat, alpha, gamma, lambda_sparsity, lambda_diversity, tolerance, obj_tol_rel, max_iter, max_iter_admm, model, x0_, eigen_cache_)
}

