// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Matrix_Mult
Eigen::MatrixXd Matrix_Mult(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> B, int n_cores);
RcppExport SEXP _ECSLRx_Matrix_Mult(SEXP ASEXP, SEXP BSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(Matrix_Mult(A, B, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// Matrix_crossprod
Eigen::MatrixXd Matrix_crossprod(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> B, int n_cores);
RcppExport SEXP _ECSLRx_Matrix_crossprod(SEXP ASEXP, SEXP BSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(Matrix_crossprod(A, B, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// Soft
Eigen::VectorXd Soft(const Eigen::VectorXd& z, const Eigen::VectorXd& gamma);
RcppExport SEXP _ECSLRx_Soft(SEXP zSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(Soft(z, gamma));
    return rcpp_result_gen;
END_RCPP
}
// group_norm
Eigen::VectorXd group_norm(const Eigen::VectorXd& s, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix);
RcppExport SEXP _ECSLRx_group_norm(SEXP sSEXP, SEXP Group_MatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(group_norm(s, Group_Matrix));
    return rcpp_result_gen;
END_RCPP
}
// group_soft_thresh
Eigen::VectorXd group_soft_thresh(const Eigen::VectorXd& vv, const Eigen::VectorXd& ue, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix);
RcppExport SEXP _ECSLRx_group_soft_thresh(SEXP vvSEXP, SEXP ueSEXP, SEXP Group_MatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type vv(vvSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ue(ueSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(group_soft_thresh(vv, ue, Group_Matrix));
    return rcpp_result_gen;
END_RCPP
}
// sigmoid
Eigen::VectorXd sigmoid(const Eigen::VectorXd& z);
RcppExport SEXP _ECSLRx_sigmoid(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(sigmoid(z));
    return rcpp_result_gen;
END_RCPP
}
// Compute_penalty_sparsity_Lasso
double Compute_penalty_sparsity_Lasso(const int& m, const Eigen::MatrixXd& betas, const Eigen::Map<Eigen::VectorXd> w_lasso, const double& lambda_lasso);
RcppExport SEXP _ECSLRx_Compute_penalty_sparsity_Lasso(SEXP mSEXP, SEXP betasSEXP, SEXP w_lassoSEXP, SEXP lambda_lassoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_lasso(w_lassoSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_lasso(lambda_lassoSEXP);
    rcpp_result_gen = Rcpp::wrap(Compute_penalty_sparsity_Lasso(m, betas, w_lasso, lambda_lasso));
    return rcpp_result_gen;
END_RCPP
}
// Compute_penalty_sparsity_groupLasso
double Compute_penalty_sparsity_groupLasso(const int& m, const Eigen::MatrixXd& betas, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::VectorXd> w_group, const double& lambda_group);
RcppExport SEXP _ECSLRx_Compute_penalty_sparsity_groupLasso(SEXP mSEXP, SEXP betasSEXP, SEXP Group_MatrixSEXP, SEXP w_groupSEXP, SEXP lambda_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_group(w_groupSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_group(lambda_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(Compute_penalty_sparsity_groupLasso(m, betas, Group_Matrix, w_group, lambda_group));
    return rcpp_result_gen;
END_RCPP
}
// Compute_penalty_fused
double Compute_penalty_fused(const int& m, const Eigen::MatrixXd& betas, const Eigen::Map<Eigen::SparseMatrix<double>> fused_penmat, const double& lambda_fused);
RcppExport SEXP _ECSLRx_Compute_penalty_fused(SEXP mSEXP, SEXP betasSEXP, SEXP fused_penmatSEXP, SEXP lambda_fusedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type fused_penmat(fused_penmatSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_fused(lambda_fusedSEXP);
    rcpp_result_gen = Rcpp::wrap(Compute_penalty_fused(m, betas, fused_penmat, lambda_fused));
    return rcpp_result_gen;
END_RCPP
}
// Compute_penalty_diversity_group
double Compute_penalty_diversity_group(const int& m, const Eigen::MatrixXd& betas, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::VectorXd> w_group, const double& lambda_diversity);
RcppExport SEXP _ECSLRx_Compute_penalty_diversity_group(SEXP mSEXP, SEXP betasSEXP, SEXP Group_MatrixSEXP, SEXP w_groupSEXP, SEXP lambda_diversitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_group(w_groupSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_diversity(lambda_diversitySEXP);
    rcpp_result_gen = Rcpp::wrap(Compute_penalty_diversity_group(m, betas, Group_Matrix, w_group, lambda_diversity));
    return rcpp_result_gen;
END_RCPP
}
// Compute_AEC
double Compute_AEC(const Eigen::VectorXd& scores, const Eigen::Map<Eigen::VectorXd> y, const Eigen::Map<Eigen::MatrixXd> cost_matrix);
RcppExport SEXP _ECSLRx_Compute_AEC(SEXP scoresSEXP, SEXP ySEXP, SEXP cost_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type cost_matrix(cost_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(Compute_AEC(scores, y, cost_matrix));
    return rcpp_result_gen;
END_RCPP
}
// Compute_objective_multi
double Compute_objective_multi(const int& m, const Eigen::Map<Eigen::MatrixXd> x_std, const Eigen::Map<Eigen::VectorXd> y, const Eigen::Map<Eigen::MatrixXd> cost_matrix, const double& lambda_lasso, const double& lambda_group, const double& lambda_fused, const double& lambda_diversity, const Eigen::Map<Eigen::VectorXd> w_lasso, const Eigen::Map<Eigen::VectorXd> w_group, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::SparseMatrix<double>> fused_penmat, const Eigen::MatrixXd& betas, const Eigen::RowVectorXd& intercept);
RcppExport SEXP _ECSLRx_Compute_objective_multi(SEXP mSEXP, SEXP x_stdSEXP, SEXP ySEXP, SEXP cost_matrixSEXP, SEXP lambda_lassoSEXP, SEXP lambda_groupSEXP, SEXP lambda_fusedSEXP, SEXP lambda_diversitySEXP, SEXP w_lassoSEXP, SEXP w_groupSEXP, SEXP Group_MatrixSEXP, SEXP fused_penmatSEXP, SEXP betasSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type x_std(x_stdSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type cost_matrix(cost_matrixSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_lasso(lambda_lassoSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_group(lambda_groupSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_fused(lambda_fusedSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_diversity(lambda_diversitySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_lasso(w_lassoSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_group(w_groupSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type fused_penmat(fused_penmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::RowVectorXd& >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(Compute_objective_multi(m, x_std, y, cost_matrix, lambda_lasso, lambda_group, lambda_fused, lambda_diversity, w_lasso, w_group, Group_Matrix, fused_penmat, betas, intercept));
    return rcpp_result_gen;
END_RCPP
}
// Compute_objective_ensemble_multi
double Compute_objective_ensemble_multi(const int& M, const Eigen::Map<Eigen::MatrixXd> x_std, const Eigen::Map<Eigen::VectorXd> y, const Eigen::Map<Eigen::MatrixXd> cost_matrix, const double& lambda_lasso, const double& lambda_group, const double& lambda_fused, const double& lambda_diversity, const Eigen::Map<Eigen::VectorXd> w_lasso, const Eigen::Map<Eigen::VectorXd> w_group, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::SparseMatrix<double>> fused_penmat, const Eigen::MatrixXd& betas, const Eigen::RowVectorXd& intercept);
RcppExport SEXP _ECSLRx_Compute_objective_ensemble_multi(SEXP MSEXP, SEXP x_stdSEXP, SEXP ySEXP, SEXP cost_matrixSEXP, SEXP lambda_lassoSEXP, SEXP lambda_groupSEXP, SEXP lambda_fusedSEXP, SEXP lambda_diversitySEXP, SEXP w_lassoSEXP, SEXP w_groupSEXP, SEXP Group_MatrixSEXP, SEXP fused_penmatSEXP, SEXP betasSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type x_std(x_stdSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type cost_matrix(cost_matrixSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_lasso(lambda_lassoSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_group(lambda_groupSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_fused(lambda_fusedSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_diversity(lambda_diversitySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_lasso(w_lassoSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_group(w_groupSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type fused_penmat(fused_penmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< const Eigen::RowVectorXd& >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(Compute_objective_ensemble_multi(M, x_std, y, cost_matrix, lambda_lasso, lambda_group, lambda_fused, lambda_diversity, w_lasso, w_group, Group_Matrix, fused_penmat, betas, intercept));
    return rcpp_result_gen;
END_RCPP
}
// admm_flasso
Eigen::VectorXd admm_flasso(const Eigen::VectorXd& vv, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::SparseMatrix<double>> Adjust_Matrix_Fused, const Eigen::VectorXd& lambda_3, const Eigen::Map<Eigen::SparseMatrix<double>> fused_penmat, const Eigen::SparseMatrix<double>& Q, const Eigen::VectorXd& eigval, const int& max_iter_admm, const Eigen::VectorXd& betas_old, const Eigen::VectorXd& numfused, const Eigen::VectorXd& df, int& iter_count);
RcppExport SEXP _ECSLRx_admm_flasso(SEXP vvSEXP, SEXP Group_MatrixSEXP, SEXP Adjust_Matrix_FusedSEXP, SEXP lambda_3SEXP, SEXP fused_penmatSEXP, SEXP QSEXP, SEXP eigvalSEXP, SEXP max_iter_admmSEXP, SEXP betas_oldSEXP, SEXP numfusedSEXP, SEXP dfSEXP, SEXP iter_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type vv(vvSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Adjust_Matrix_Fused(Adjust_Matrix_FusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambda_3(lambda_3SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type fused_penmat(fused_penmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eigval(eigvalSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter_admm(max_iter_admmSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betas_old(betas_oldSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type numfused(numfusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int& >::type iter_count(iter_countSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_flasso(vv, Group_Matrix, Adjust_Matrix_Fused, lambda_3, fused_penmat, Q, eigval, max_iter_admm, betas_old, numfused, df, iter_count));
    return rcpp_result_gen;
END_RCPP
}
// compute_block_eigen
Rcpp::List compute_block_eigen(const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::SparseMatrix<double>> Adjust_Matrix_Fused, const Eigen::Map<Eigen::SparseMatrix<double>> fused_penmat);
RcppExport SEXP _ECSLRx_compute_block_eigen(SEXP Group_MatrixSEXP, SEXP Adjust_Matrix_FusedSEXP, SEXP fused_penmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Adjust_Matrix_Fused(Adjust_Matrix_FusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type fused_penmat(fused_penmatSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_block_eigen(Group_Matrix, Adjust_Matrix_Fused, fused_penmat));
    return rcpp_result_gen;
END_RCPP
}
// update_betas
Eigen::VectorXd update_betas(const Eigen::VectorXd& vv, const Eigen::VectorXd& betas_old, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::SparseMatrix<double>> Adjust_Matrix_Fused, const Eigen::Map<Eigen::SparseMatrix<double>> fused_penmat, const Eigen::SparseMatrix<double>& Q, const Eigen::VectorXd& eigval, const Eigen::VectorXd& numfused, const Eigen::VectorXd& df, const int& max_iter_admm, const double& lambda_lasso, const Eigen::Map<Eigen::VectorXd> w_lasso, const double& lambda_fused, const Eigen::VectorXd& group_soft_penalty, const Eigen::VectorXd& eta_m, const bool& exist_grouplasso, Eigen::VectorXd& lambda_1w, Eigen::VectorXd& lambda_2, Eigen::VectorXd& lambda_3);
RcppExport SEXP _ECSLRx_update_betas(SEXP vvSEXP, SEXP betas_oldSEXP, SEXP Group_MatrixSEXP, SEXP Adjust_Matrix_FusedSEXP, SEXP fused_penmatSEXP, SEXP QSEXP, SEXP eigvalSEXP, SEXP numfusedSEXP, SEXP dfSEXP, SEXP max_iter_admmSEXP, SEXP lambda_lassoSEXP, SEXP w_lassoSEXP, SEXP lambda_fusedSEXP, SEXP group_soft_penaltySEXP, SEXP eta_mSEXP, SEXP exist_grouplassoSEXP, SEXP lambda_1wSEXP, SEXP lambda_2SEXP, SEXP lambda_3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type vv(vvSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betas_old(betas_oldSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Adjust_Matrix_Fused(Adjust_Matrix_FusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type fused_penmat(fused_penmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eigval(eigvalSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type numfused(numfusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter_admm(max_iter_admmSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_lasso(lambda_lassoSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_lasso(w_lassoSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_fused(lambda_fusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type group_soft_penalty(group_soft_penaltySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eta_m(eta_mSEXP);
    Rcpp::traits::input_parameter< const bool& >::type exist_grouplasso(exist_grouplassoSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type lambda_1w(lambda_1wSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type lambda_2(lambda_2SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type lambda_3(lambda_3SEXP);
    rcpp_result_gen = Rcpp::wrap(update_betas(vv, betas_old, Group_Matrix, Adjust_Matrix_Fused, fused_penmat, Q, eigval, numfused, df, max_iter_admm, lambda_lasso, w_lasso, lambda_fused, group_soft_penalty, eta_m, exist_grouplasso, lambda_1w, lambda_2, lambda_3));
    return rcpp_result_gen;
END_RCPP
}
// update_betas_with_iter
Rcpp::List update_betas_with_iter(const Eigen::VectorXd& vv, const Eigen::VectorXd& betas_old, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::SparseMatrix<double>> Adjust_Matrix_Fused, const Eigen::Map<Eigen::SparseMatrix<double>> fused_penmat, const Eigen::SparseMatrix<double>& Q, const Eigen::VectorXd& eigval, const Eigen::VectorXd& numfused, const Eigen::VectorXd& df, const int& max_iter_admm, const double& lambda_lasso, const Eigen::Map<Eigen::VectorXd> w_lasso, const double& lambda_fused, const Eigen::VectorXd& group_soft_penalty, const Eigen::VectorXd& eta_m, const bool& exist_grouplasso);
RcppExport SEXP _ECSLRx_update_betas_with_iter(SEXP vvSEXP, SEXP betas_oldSEXP, SEXP Group_MatrixSEXP, SEXP Adjust_Matrix_FusedSEXP, SEXP fused_penmatSEXP, SEXP QSEXP, SEXP eigvalSEXP, SEXP numfusedSEXP, SEXP dfSEXP, SEXP max_iter_admmSEXP, SEXP lambda_lassoSEXP, SEXP w_lassoSEXP, SEXP lambda_fusedSEXP, SEXP group_soft_penaltySEXP, SEXP eta_mSEXP, SEXP exist_grouplassoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type vv(vvSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type betas_old(betas_oldSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Adjust_Matrix_Fused(Adjust_Matrix_FusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type fused_penmat(fused_penmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eigval(eigvalSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type numfused(numfusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter_admm(max_iter_admmSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_lasso(lambda_lassoSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_lasso(w_lassoSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_fused(lambda_fusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type group_soft_penalty(group_soft_penaltySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eta_m(eta_mSEXP);
    Rcpp::traits::input_parameter< const bool& >::type exist_grouplasso(exist_grouplassoSEXP);
    rcpp_result_gen = Rcpp::wrap(update_betas_with_iter(vv, betas_old, Group_Matrix, Adjust_Matrix_Fused, fused_penmat, Q, eigval, numfused, df, max_iter_admm, lambda_lasso, w_lasso, lambda_fused, group_soft_penalty, eta_m, exist_grouplasso));
    return rcpp_result_gen;
END_RCPP
}
// ECSLR_Compute_Coef_combine
List ECSLR_Compute_Coef_combine(const Eigen::Map<Eigen::MatrixXd> x, const Eigen::Map<Eigen::VectorXd> y, const Eigen::Map<Eigen::MatrixXd> cost_matrix, const int& M, const bool& include_intercept, const Eigen::Map<Eigen::VectorXd> w_lasso, const Eigen::Map<Eigen::SparseMatrix<double>> Group_Matrix, const Eigen::Map<Eigen::VectorXd> w_group, const Eigen::Map<Eigen::SparseMatrix<double>> Adjust_Matrix_Fused, const Eigen::Map<Eigen::SparseMatrix<double>> fused_penmat, const double& alpha, const double& gamma, const double& lambda_sparsity, const double& lambda_diversity, const double& tolerance, const double& obj_tol_rel, const int& max_iter, const int& max_iter_admm, const std::string& model, const Rcpp::Nullable<Rcpp::List>& x0_, const Rcpp::Nullable<Rcpp::List>& eigen_cache_);
RcppExport SEXP _ECSLRx_ECSLR_Compute_Coef_combine(SEXP xSEXP, SEXP ySEXP, SEXP cost_matrixSEXP, SEXP MSEXP, SEXP include_interceptSEXP, SEXP w_lassoSEXP, SEXP Group_MatrixSEXP, SEXP w_groupSEXP, SEXP Adjust_Matrix_FusedSEXP, SEXP fused_penmatSEXP, SEXP alphaSEXP, SEXP gammaSEXP, SEXP lambda_sparsitySEXP, SEXP lambda_diversitySEXP, SEXP toleranceSEXP, SEXP obj_tol_relSEXP, SEXP max_iterSEXP, SEXP max_iter_admmSEXP, SEXP modelSEXP, SEXP x0_SEXP, SEXP eigen_cache_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type cost_matrix(cost_matrixSEXP);
    Rcpp::traits::input_parameter< const int& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const bool& >::type include_intercept(include_interceptSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_lasso(w_lassoSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Group_Matrix(Group_MatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type w_group(w_groupSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type Adjust_Matrix_Fused(Adjust_Matrix_FusedSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double>> >::type fused_penmat(fused_penmatSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_sparsity(lambda_sparsitySEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_diversity(lambda_diversitySEXP);
    Rcpp::traits::input_parameter< const double& >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const double& >::type obj_tol_rel(obj_tol_relSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter_admm(max_iter_admmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type x0_(x0_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type eigen_cache_(eigen_cache_SEXP);
    rcpp_result_gen = Rcpp::wrap(ECSLR_Compute_Coef_combine(x, y, cost_matrix, M, include_intercept, w_lasso, Group_Matrix, w_group, Adjust_Matrix_Fused, fused_penmat, alpha, gamma, lambda_sparsity, lambda_diversity, tolerance, obj_tol_rel, max_iter, max_iter_admm, model, x0_, eigen_cache_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ECSLRx_Matrix_Mult", (DL_FUNC) &_ECSLRx_Matrix_Mult, 3},
    {"_ECSLRx_Matrix_crossprod", (DL_FUNC) &_ECSLRx_Matrix_crossprod, 3},
    {"_ECSLRx_Soft", (DL_FUNC) &_ECSLRx_Soft, 2},
    {"_ECSLRx_group_norm", (DL_FUNC) &_ECSLRx_group_norm, 2},
    {"_ECSLRx_group_soft_thresh", (DL_FUNC) &_ECSLRx_group_soft_thresh, 3},
    {"_ECSLRx_sigmoid", (DL_FUNC) &_ECSLRx_sigmoid, 1},
    {"_ECSLRx_Compute_penalty_sparsity_Lasso", (DL_FUNC) &_ECSLRx_Compute_penalty_sparsity_Lasso, 4},
    {"_ECSLRx_Compute_penalty_sparsity_groupLasso", (DL_FUNC) &_ECSLRx_Compute_penalty_sparsity_groupLasso, 5},
    {"_ECSLRx_Compute_penalty_fused", (DL_FUNC) &_ECSLRx_Compute_penalty_fused, 4},
    {"_ECSLRx_Compute_penalty_diversity_group", (DL_FUNC) &_ECSLRx_Compute_penalty_diversity_group, 5},
    {"_ECSLRx_Compute_AEC", (DL_FUNC) &_ECSLRx_Compute_AEC, 3},
    {"_ECSLRx_Compute_objective_multi", (DL_FUNC) &_ECSLRx_Compute_objective_multi, 14},
    {"_ECSLRx_Compute_objective_ensemble_multi", (DL_FUNC) &_ECSLRx_Compute_objective_ensemble_multi, 14},
    {"_ECSLRx_admm_flasso", (DL_FUNC) &_ECSLRx_admm_flasso, 12},
    {"_ECSLRx_compute_block_eigen", (DL_FUNC) &_ECSLRx_compute_block_eigen, 3},
    {"_ECSLRx_update_betas", (DL_FUNC) &_ECSLRx_update_betas, 19},
    {"_ECSLRx_update_betas_with_iter", (DL_FUNC) &_ECSLRx_update_betas_with_iter, 16},
    {"_ECSLRx_ECSLR_Compute_Coef_combine", (DL_FUNC) &_ECSLRx_ECSLR_Compute_Coef_combine, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_ECSLRx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
